# _config.yml (修正版)
collections:
  blogs:
    output: true
    permalink: /blogs/:path/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: default
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
  # 添加对根目录下 Markdown 文件的默认布局
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

permalink: pretty
include:
  - '_blogs'
  - '_projects'
  - '_layouts'
  - 'assets'
  - 'js'
  - 'images'
  - 'css'
  - 'fonts'
  - 'favicon.ico'
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - '.git'
  - '.github'

# Markdown处理
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3

# 插件配置 - 只保留 GitHub Pages 支持的插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# 分页配置
paginate: 5
paginate_path: "/page/:num/"

# 添加基础 URL 配置，如果您使用自定义域名，可以留空
baseurl: ""